### ISSUE TITLE
makePrefix 위치

### ISSUE THREAD

**Issue by moong2** [42Seoul-IRC/ft_irc#12]
makePrefix의 인자로 Client객체가 들어가는데 Message 클래스는 Client객체 참조가 불가능하네요
<img width="562" alt="image" src="https://github.com/42Seoul-IRC/ft_irc/assets/67732143/53edc8ae-219e-478e-aa5b-1e35e239d212">

Client객체에서 makeHost 함수로 std::string 형태의 'root@127.0.0.1'를 반환하는 건 어떨까요?
<img width="754" alt="image" src="https://github.com/42Seoul-IRC/ft_irc/assets/67732143/9cb6ab28-a051-4f47-b4c8-5db920ef6425">

-> Client객체에는 이미 getHost()라는 함수가 있는데 이건 127.0.0.1을 std::string형태로 반환하고 있습니다. 
이 함수를 수정해서  \<username>!\<hostname>@\<hostIP>의 형태로 std::string을 반환하고 사용하는 건 어떨까요?

**Comment by tg201005** [comment]
check
