### ISSUE TITLE
접속 시 PASS, NICK, USER 인증 여부

### ISSUE THREAD

**Issue by moong2** [42Seoul-IRC/ft_irc#13]
접속 시 PASS, NICK, USER 순서로 인증을 완료해야하는데

Client객체에
PASS 여부 -> is_pass_
NICK 여부 -> is_nick_ (혹은 std::string nickname == "" 로 확인)
USER 여부 -> is_user_ (혹은 std::string username==""로 확인)

위 세가지가 모두 통과됨이 확인되면
is_authenticated_를 true로 설정하는건 어떤가요?

* 현재는 is_authenticated_만 존재해서 인증 순서를 고려하지 않습니다!

**Comment by Tolerblanc** [comment]
PASS가 맨 먼저 이뤄져야 하는 것은 맞는 것 같은데, netcat으로 확인해보니 NICK과 USER의 순서는 바뀌어도 작동하는 것 같습니다. irssi 기준으로는 순서가 정해져 있긴 한데, 이 부분은 같이 이야기 해보면 좋을 것 같네요

**Comment by tg201005** [comment]
제가 하죠
