### ISSUE TITLE
Error Message 과다(?) 문제

### ISSUE THREAD

**Issue by moong2** [42Seoul-IRC/ft_irc#14]
만들다보니 Commands.cpp가 에러메시지로 난장판이네요..

이건 그냥 이사 개념이긴 합니다만
<img width="617" alt="image" src="https://github.com/42Seoul-IRC/ft_irc/assets/67732143/68774fda-718e-4be5-90bd-24317b6fa57d">
<img width="428" alt="image" src="https://github.com/42Seoul-IRC/ft_irc/assets/67732143/1d549d27-b291-4b67-bd5f-b5adda31f3bf">

ErrorPacket.hpp / cpp를 만든 후 PacketManager.hpp를 include / 상속받고 Commands.cpp는 ErrorPacket.hpp를 include하면 다음과 같이 Command.cpp가 짧아지긴 합니다
--> 성공 Packet까지 여기서 만들면 PacketMaker.hpp / cpp로 이름을 바꿀 수도 있을 것 같네요

<img width="839" alt="image" src="https://github.com/42Seoul-IRC/ft_irc/assets/67732143/95385894-d5b2-4fb5-8ed8-c2bf30284ed7">
<img width="823" alt="image" src="https://github.com/42Seoul-IRC/ft_irc/assets/67732143/6bede98d-0ae7-476c-81a5-3518e376c924">

### ***어쨌든 단순 이사 개념이긴 합니다 ㅠ**

**Comment by Tolerblanc** [comment]
사진이 깨져서 안보이긴 하는데, 단순 이사로 짧아질 수 있으면 그렇게 하는게 좋은 것 같아요.
