### ISSUE TITLE
인자 받을 때, # + 등의 처리

### ISSUE THREAD

**Issue by tg201005** [42Seoul-IRC/ft_irc#16]

**Comment by Tolerblanc** [comment]
스플릿 후에 #으로 시작하면 채널 이름 확인 함수에 넣고, + 또는 - 라면 뒷 문자만 파싱해서 switch 문으로 모드 변경해주면 될 것 같은데, 어떻게 생각하시나요?

**Comment by tg201005** [comment]
# 처리 안합니다
