### ISSUE TITLE
채널 객체가 제대로 생성되지 않는 문제

### ISSUE THREAD

**Issue by Tolerblanc** [42Seoul-IRC/ft_irc#22]
인증 과정을 거친 후, join 명령어를 사용하면 바로 서버가 터집니다.

**Comment by Tolerblanc** [comment]
객체 자체는 제대로 생성되고 있는데, 아까 PacketMaker - PacketManager 에서 터졌던 문제와 같은 원리인 것 같습니다.
PacketManager->channel_manager_ 에는 채널 객체를 생성하여 저장했는데, 이 시점이 PacketMaker 생성 이후라서 SEGV가 터집니다...

**Comment by Tolerblanc** [comment]
[INFO] Create channel : #test, 0x104203d40
[INFO] client_manager_ : 0x16ee9ac20
[INFO] channel_manager_ : 0x16ee9ac08
[DEBUG] RPlNamReply : 5, 0x104102a30, #test, 0x104203d40
sendPacket: 0x16ee991f8

PacketMaker의 channel_manager_와 client_manager_를 레퍼런스로 바꿨는데,
PacketManager의 클라이언트 매니저 == PacketMaker의 클라이언트 매니저 != PacketManager->sendPacket()의 클라이언트 매니저 인 상황입니다.

**Comment by Tolerblanc** [comment]
일단 PacketManager->sendPacket() 와 PacketMaker->sendPacket() 가 다르다고 생각중인데, 클러에서 마저 추적해볼게요

**Comment by moong2** [comment]
생각해보니 PacketMaker를 PacketManager가 상속받을 게 아니라 PacketMaker의 생성자를 만들고 clientmanager, channelmanager, process각 함수의 packet을 전달하면 되지 않을까요?

**Comment by Tolerblanc** [comment]
> 클래스도 레퍼런스 적용이 되나요? 
- 이니셜라이저로 초기화 하면 사용은 가능합니다.
> 생각해보니 PacketMaker를 PacketManager가 상속받을 게 아니라 PacketMaker의 생성자를 만들고 clientmanager, channelmanager, process각 함수의 packet을 전달하면 되지 않을까요?
- PacketMaker의 channel_manager_와 client_manager_를 레퍼런스로 바꾸는 것과 큰 차이가 있는지 잘 모르겠네요.

그림을 쭉 그려보니까 설계 미스가 좀 있는데, 클러 오셨을 때 같이 보시면 좋을 것 같습니다

**Comment by Tolerblanc** [comment]
#26 , #27 을 통해 수정 완료하였습니다.
