### ISSUE TITLE
Welcome 메시지 형식이 뒤집혀 있는 버그

### ISSUE THREAD

**Issue by Tolerblanc** [42Seoul-IRC/ft_irc#23]
<img width="296" alt="image" src="https://github.com/42Seoul-IRC/ft_irc/assets/52883827/3cca1dde-6c74-4e40-a7bc-71332f0113fa">

사소해보이지만 뭔가 요상하게 생겨서 올려봅니닷

**Comment by moong2** [comment]
"<client> :Welcome to the <networkname> Network, <nick>[!<user>@<host>]"

실제 모던irc에서 제공한 형식은 다음과같습니다!

저희가 참고했던 tcpflow를 보고 저렇게 만들었던 것 같은데 내일 가서 한번 다시 확인해볼게요

**Comment by moong2** [comment]
<img width="533" alt="image" src="https://github.com/42Seoul-IRC/ft_irc/assets/67732143/de965e34-0489-499b-8b4d-a6d9dd5a11ba">
앞에 서버네임만 붙여서 출력하면 될 듯 합니다!
고치고 이슈 닫겠습니다~
