### ISSUE TITLE
명령 처리 속도가 너무 느린 문제

### ISSUE THREAD

**Issue by Tolerblanc** [42Seoul-IRC/ft_irc#29]
클라이언트 수가 적음에도 지금 처리 속도가 지나치게 느린 것 같습니다. 
최적화 할 만한 부분을 같이 찾아보면 좋을 것 같아요.

**Comment by moong2** [comment]
어제는 느리다고 생각했는데 제 로컬에서 테스트해볼 땐 시간 1초도 안걸려서 바로 뜨네요
어제는 도커 위에 올려서 느렸던 걸까요?

**Comment by Tolerblanc** [comment]
그러게요... 제 로컬에서도 딱히 속도 이슈는 없는 것 같습니다. 왜 클러에서는 느렸는 지 잘 모르겠네요.
`std::string` 인자로 가져갈 때 복사하는 부분이 많은 것 같아서, 이 부분만 수정해주면 더 개선할 사항은 없어보입니다.

**Comment by moong2** [comment]
갑자기 엄청 느려졌는데 이유가 왜일까요?
한 클라이언트가 join #ch1을 하는 순간은 빠른데 join #ch2부터는 MODE input이 어어엄청 느리게 오네요

**Comment by Tolerblanc** [comment]
느려지는 조건 자체에 대해 갈피를 잘 못잡겠습니다. 메시지 도배해도 어느 때에는 잘 처리하고, 어느 때에는 너무 밀려서 확인 조차 힘들때가 있습니다

**Comment by moong2** [comment]
최적화 문제가 아니라는 생각이 드는게 mode를 합치기 전 커밋으로 돌려봤는데 join 이후 mode 입력 자체가 늦게 오는 것 같네요

**Comment by moong2** [comment]
recv 함수 밑에 바로 찍어봤는데 아무 입력이 없는 걸 보니 irssi 내부의 문제 같습니다. 일단 이슈 닫겠습니다
이후 원인을 찾게된다면 다시 열어주세요
