### ISSUE TITLE
irssi를 통해 접근할 때, 인자를 완벽하게 주지 않으면 무한 루프가 생기는 버그

### ISSUE THREAD

**Issue by Tolerblanc** [42Seoul-IRC/ft_irc#32]
irssi의 인자를 부족하게 작동시키면 무한 루프가 생기다가 서버가 죽습니다.

**Comment by moong2** [comment]
@Tolerblanc @tg201005 

새로운 사실인데 처음에 인자를 빼먹어서 접속이 안되었을 때 다음과 같이 주면 다시 접속이 가능합니다

/connect 127.0.0.1 3555 hi nick

LOG] {10 -> irc.webserv} - CAP LS
[LOG] {10 -> irc.webserv} - PASS hi
[LOG] {10 -> irc.webserv} - NICK nick
[LOG] {10 -> irc.webserv} - USER seongha seongha 127.0.0.1 :박성하
[LOG] {irc.webserv -> 10} - 001 nick :Welcome to the server nick!seongha@127.0.0.1

로그도 이렇게 잘 찍히네요

**Comment by Tolerblanc** [comment]
혹시 이 버그 재현 가능한가요?? 계속 해봐도 재현 자체가 불가능한데....?

**Comment by moong2** [comment]
그리고 해당 문제는 제 컴퓨터에선 발견되지 않네요..ㅜ

**Comment by moong2** [comment]
기억상으론 ./ircserv 4242 4242로 두셨던 거 같은데 아무리 해봐도 안되네요..? 내가 본 것은 뭐였지

**Comment by Tolerblanc** [comment]
@tg201005  help...

**Comment by moong2** [comment]
그리고 다시 접속할 때 nick안줘도 자꾸 전에 쓰던 nick 가져다 주는데 왜이런걸까요
물론 서버 문제는 아니고 클라가 알아서 넘겨주는 거긴 한데

**Comment by Tolerblanc** [comment]
`~/.irssi/config` 요 설정 파일과 관련이 있어보이긴 합니다

**Comment by moong2** [comment]
@tg201005 여기봐주셍요
⢀⣠⣾⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⠀⠀⠀⠀⣠⣤⣶⣶
⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⠀⠀⠀⢰⣿⣿⣿⣿
⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣧⣀⣀⣾⣿⣿⣿⣿
⣿⣿⣿⣿⣿⡏⠉⠛⢿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡿⣿
⣿⣿⣿⣿⣿⣿⠀⠀⠀⠈⠛⢿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⠿⠛⠉⠁⠀⣿
⣿⣿⣿⣿⣿⣿⣧⡀⠀⠀⠀⠀⠙⠿⠿⠿⠻⠿⠿⠟⠿⠛⠉⠀⠀⠀⠀⠀⣸⣿
⣿⣿⣿⣿⣿⣿⣿⣷⣄⠀⡀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢀⣴⣿⣿
⣿⣿⣿⣿⣿⣿⣿⣿⣿⠏⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠠⣴⣿⣿⣿⣿
⣿⣿⣿⣿⣿⣿⣿⣿⡟⠀⠀⢰⣹⡆⠀⠀⠀⠀⠀⠀⣭⣷⠀⠀⠀⠸⣿⣿⣿⣿
⣿⣿⣿⣿⣿⣿⣿⣿⠃⠀⠀⠈⠉⠀⠀⠤⠄⠀⠀⠀⠉⠁⠀⠀⠀⠀⢿⣿⣿⣿
⣿⣿⣿⣿⣿⣿⣿⣿⢾⣿⣷⠀⠀⠀⠀⡠⠤⢄⠀⠀⠀⠠⣿⣿⣷⠀⢸⣿⣿⣿
⣿⣿⣿⣿⣿⣿⣿⣿⡀⠉⠀⠀⠀⠀⠀⢄⠀⢀⠀⠀⠀⠀⠉⠉⠁⠀⠀⣿⣿⣿
⣿⣿⣿⣿⣿⣿⣿⣿⣧⠀⠀⠀⠀⠀⠀⠀⠈⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢹⣿⣿
⣿⣿⣿⣿⣿⣿⣿⣿⣿⠃⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢸⣿⣿

**Comment by tg201005** [comment]
<img width="1288" alt="Screen Shot 2023-07-22 at 10 50 28 PM" src="https://github.com/42Seoul-IRC/ft_irc/assets/84652799/ea4f39f6-1cea-435b-9da0-2dc37df8a0a1">

아직 merge가 안된 상태여서, 내일 다시 확인해보죠! 일단 지금도 저는 같은 문제가 반복됩니당

**Comment by moong2** [comment]
인자 어떻게 주셨나요?
