### ISSUE TITLE
[터지는 문제] 동일한 nick에 대한 파싱 문제

### ISSUE THREAD

**Issue by tg201005** [42Seoul-IRC/ft_irc#33]
서버 키고, 똑같은 이름으로 접속했을 때 파싱 문제

**Comment by moong2** [comment]
':' 이 문자도 처리를 해주는게 좋을까요?
<img width="693" alt="image" src="https://github.com/42Seoul-IRC/ft_irc/assets/67732143/ede8b486-e8ee-4d4d-9330-1d77ff441d0c">

/nick hi:hi 시 hi로 닉네임이 바뀌긴합니다

**Comment by Tolerblanc** [comment]
콜론도 스페셜 캐릭터로 쓰이니까 헷갈릴 여지가 있긴 하겠네요. 막으면 좋을 것 같습니다!

**Comment by Tolerblanc** [comment]
#42 에서 해결 후 머지되었습니다
