### ISSUE TITLE
system error 시 일관성 문제

### ISSUE THREAD

**Issue by moong2** [42Seoul-IRC/ft_irc#43]
bind는 현재 try catch로 잡고 exit(EXIT_FAILURE)하도록 설정되어 있는데
fcntl은 다음과 같이 뻥 터져버립니다

같은 시스템 에러인데 어떻게 처리하는게 좋을까요?
<img width="665" alt="image" src="https://github.com/42Seoul-IRC/ft_irc/assets/67732143/e776ad20-7ea3-431f-b63a-d6a8e8da8c51">

**Comment by Tolerblanc** [comment]
음... 그냥 exit으로 처리 하는게 맞을까요? 아니면 아예 메인에서 try-catch 걸고 return(1) 해주는 것도 괜찮을 것 같습니다.

**Comment by Tolerblanc** [comment]
둘 중 아무거나 해도 상관은 없겠네용
