### ISSUE TITLE
Invite mode가 켜져있을 때, irrsi 반응이 다른 문제 #tyi last #40

### ISSUE THREAD

**Issue by tg201005** [42Seoul-IRC/ft_irc#44]
채널에 i 옵션을 주고, join으로 접근시 저희 irssi 창은 검은 화면이 나오네요. 

메시지 문제인가 해서, 메시지를 맞추어서 보내보았는데도 현상은 동일합니다. 같이 확인해보시죠 Tyi last #40
<img width="1932" alt="Screen Shot 2023-07-22 at 8 01 20 PM" src="https://github.com/42Seoul-IRC/ft_irc/assets/84652799/71fdf5a2-18c5-4bb2-b6ae-99155f90c7dd">

[b98f8ae223dd0f23258d599012d5061711ff094a](https://github.com/42Seoul-IRC/ft_irc/commit/eaa7d4e6a5b20744777cc5b7fe2cc38fa7c7d2e4)

**Comment by Tolerblanc** [comment]
오늘은 6미널만 쓰시는군요! 적어주신 이슈들 차근차근 읽어보겠습니다

**Comment by Tolerblanc** [comment]
+l 옵션 줘도 위처럼 작동하네요...? 저희 서버 문제가 아니라 클라이언트 문제일 수도 있을 것 같습니다.
클라이언트 메인 페이지에는 정상적으로 응답 코드가 쌓이고 있습니다.

**Comment by Tolerblanc** [comment]
Response Message에 채널 이름이 빠져서 생기는 문제였습니다. 위 커밋으로 해결 완료!
