### ISSUE TITLE
mode +k 설정되어있을 때 join 하려하면 segv 

### ISSUE THREAD

**Issue by tg201005** [42Seoul-IRC/ft_irc#45]
<img width="616" alt="Screen Shot 2023-07-22 at 8 33 33 PM" src="https://github.com/42Seoul-IRC/ft_irc/assets/84652799/1eedffb4-81b4-4a3a-9890-21dea39c4ee3">

이것도 한 번 같이 찾아보시죠!

**Comment by tg201005** [comment]
비밀번호를 치고 입력하면, 정상적으로 잘 들어가집니다

**Comment by tg201005** [comment]
그냥 join #채널 할 때만 터지네요

**Comment by tg201005** [comment]
<img width="422" alt="Screen Shot 2023-07-22 at 9 55 55 PM" src="https://github.com/42Seoul-IRC/ft_irc/assets/84652799/013e8ac9-a817-4fec-bf10-0146e3a5dd77">

이와 비슷한 게 또 있네요. invite only여서 거부 당하는데, 들어가서 privmsg는 한 번 전달할 수 가 있네요!

**Comment by Tolerblanc** [comment]
invite 사진만 보면 정상 동작인 것 같은데요?? #a 로 메시지를 보내려고 했으나, invite only 채널이라 접속하지 못하여 404 반환 받은 것으로 보입니다.

**Comment by Tolerblanc** [comment]
비밀번호 채널일 때 join #channel로 터지는 건 휴먼 에러 입니다...... 두번째 인자의 존재 유무도 체크 안하고 참조해버려서 터지는 것 같네요.
내일 클러스터에서 바로 수정하겠습니다.

**Comment by Tolerblanc** [comment]
위 커밋으로 수정 완료!
