### ISSUE TITLE
클라이언트가 Kick의 권한이 없을 때의 에러 메시지 전달 형식 

### ISSUE THREAD

**Issue by tg201005** [42Seoul-IRC/ft_irc#46]
operator privileges need

현재 출력 메시지 trailing 이전에 "#채널"이 미포함되어있는 듯 합니다. 제가 넣어보려했는데, 구조가 조금 어려워서 부탁드립니당.

<img width="600" alt="Screen Shot 2023-07-22 at 8 47 27 PM" src="https://github.com/42Seoul-IRC/ft_irc/assets/84652799/6794979f-9600-45a6-9d35-19370a83fecc">

<img width="625" alt="Screen Shot 2023-07-22 at 8 47 23 PM" src="https://github.com/42Seoul-IRC/ft_irc/assets/84652799/fcce1049-8591-46e0-adb0-3fc4a9aec0c9">

아마, 이를 맞추면 아래와 같은 메시지가 클라이언트 상에 뜰 거 같습니다. 현재는 메시지가 출력되지 않습니당
<img width="502" alt="Screen Shot 2023-07-22 at 8 49 45 PM" src="https://github.com/42Seoul-IRC/ft_irc/assets/84652799/a54bd30f-0903-4d85-b0d4-85f42cefd014">

**Comment by tg201005** [comment]
다른 kick 메시지 성공 출력과, 권한 설정 문제없이 돌아가고 있습니다!

**Comment by tg201005** [comment]
limit도 유사한 형식 차이가 있는 듯 합니다. 아마 같은 함수에서 처리하는 거 같은데, 그 함수 인자에 채널만 넣어주면 다른 메시지까지 모두 클라이언트에 반영될 듯 합니다!

<img width="595" alt="Screen Shot 2023-07-22 at 8 53 15 PM" src="https://github.com/42Seoul-IRC/ft_irc/assets/84652799/533ecc9e-2268-4a5d-84f6-8c75a6f5a7c7">
<img width="473" alt="Screen Shot 2023-07-22 at 8 53 31 PM" src="https://github.com/42Seoul-IRC/ft_irc/assets/84652799/45b9ecae-f9dd-417e-a3a0-863bdfac5157">

**Comment by Tolerblanc** [comment]
이거는 아마 `sendPacket()` 이전에 채널 명도 같이 넘겨주면 간단하게 해결 될 것 같은데, 해당 채널 말고 클라이언트 메인 화면에 로그가 쌓이는 지를 봐야할 것 같아요

**Comment by Tolerblanc** [comment]
위 커밋으로 메시지 형식 수정 완료했습니다!
