### ISSUE TITLE
쭉 읽어보면서 다시 한번 보고 싶은 것들 정리함

### ISSUE THREAD

**Issue by moong2** [42Seoul-IRC/ft_irc#67]
- [x] #68

**Comment by Tolerblanc** [comment]
앗.. 잘못눌러서 이슈로 바꿔버렸네요 
얘네는 스트링스트림에 스트링 넣는거라서 딱히 분리 안해도 될 것 같습니다!

**Comment by moong2** [comment]
- [ ] readme 수정 후 제출 ~!~!~@~!@~!@!@@!#~!@~! 디버깅 옵션 제외하기~!@@!#@~!
