### ISSUE TITLE
ctrl z 처리

### ISSUE THREAD

**Issue by tg201005** [42Seoul-IRC/ft_irc#69]

**Comment by Tolerblanc** [comment]
세상에... 생각도 못했던 부분이네요.
아마도 signal()을 여기다 쓰면 될 것 같네요.

https://stackoverflow.com/questions/4891214/how-to-handle-the-signal-ctrl-z-in-mini-shell-c

**Comment by tg201005** [comment]
평가표에 ctrl z 처리하라고 되어있네요 ㅠㅠ 흑

**Comment by moong2** [comment]
놀라운건 아직까지 sigtstp을 감지하지 못했다는 것입니다 glgl

**Comment by Tolerblanc** [comment]
90분 안에 처리 완료했네요! 
```bash
# 클라이언트를 Ctrl+Z로 멈췄다면
fg
# 위 명령어를 호출하여 멈춘 클라이언트에 다시 접근해본다.
```
