### ISSUE TITLE
보너?스

### ISSUE THREAD

**Issue by Tolerblanc** [42Seoul-IRC/ft_irc#72]
- [x] File Transfer with Reference Client
- [x] A bot

**Comment by Tolerblanc** [comment]
File Transfer => Direct Client-to-Client
Bot => roll-dice bot

**Comment by Tolerblanc** [comment]
https://modern.ircdocs.horse/dcc.html

**Comment by moong2** [comment]
아니 파일 도대체 왜 안열리죠?

**Comment by Tolerblanc** [comment]
> 18:11 < irc.webserv> DICE_BOT DICE: 6️⃣

현재 구현은 메시지 형식이 잘못되어 있는데, 수정이 필요합니다. prefix에 DICE_BOT을 넘기면 채널에 전달이 안됩니다.
